<a href="https://colab.research.google.com/github/KKBUGHUNTER/Image_Processing/blob/main/01_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import cv2
BW_image_path = "Images/Black_and_White_image.png"

BW_image = cv2.imread(BW_image_path)
print("Black and White Image")
print(BW_image)

Black and White Image
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [5]:
print('Height of the image', len(BW_image))
print('Width of the image', len(BW_image[1]))

Height of the image 225
Width of the image 225


In [7]:
def Neigbhor_4(x,y):
  print("       ", BW_image[x-1][y])
  print(BW_image[x][y-1],BW_image[x][y],BW_image[x][y+1])
  print("       ", BW_image[x+1][y],)

print("4 Neighbor of f(10,20): \n")
Neigbhor_4(10,20)
print("\n\n4 Neighbor of f(3,4): \n")
Neigbhor_4(3,4)

4 Neighbor of f(10,20): 

        [255 255 255]
[255 255 255] [255 255 255] [255 255 255]
        [255 255 255]


4 Neighbor of f(3,4): 

        [255 255 255]
[255 255 255] [255 255 255] [255 255 255]
        [255 255 255]


In [6]:
def Neigbhor_8(x,y):
  print(BW_image[x-1][y-1],BW_image[x-1][y],BW_image[x-1][y+1])
  print(BW_image[x][y-1],BW_image[x][y],BW_image[x][y+1])
  print(BW_image[x+1][y-1],BW_image[x+1][y],BW_image[x+1][y+1])

print("8 Neighbor of f(10,20): \n")
Neigbhor_8(10,20)
print("\n\n8 Neighbor of f(3,4): \n")
Neigbhor_8(3,4)

8 Neighbor of f(10,20): 

[255 255 255] [255 255 255] [255 255 255]
[255 255 255] [255 255 255] [255 255 255]
[255 255 255] [255 255 255] [255 255 255]


8 Neighbor of f(3,4): 

[255 255 255] [255 255 255] [255 255 255]
[255 255 255] [255 255 255] [255 255 255]
[255 255 255] [255 255 255] [255 255 255]


## Nearest Neighbor Interpolation